package com.jocmp.mercury.utils.dom

import com.jocmp.mercury.dsl.Doc
import kotlin.test.Test
import kotlin.test.assertEquals

class IsWordpressTest {
    @Test
    fun `returns false if a site is not generated by wordpress`() {
        val html = """
          <html>
            <head>
              <meta name="generator" value="whatever">
            <head>
          </html>
        """
        var doc = Doc.load(html, isDocument = false)
        assertEquals(false, isWordpress(doc))

        val html2 = """
          <html>
            <head>
              <meta name="foo" value="bar">
            <head>
          </html>
        """
        doc = Doc.load(html2, isDocument = false)
        assertEquals(false, isWordpress(doc))
    }

    @Test
    fun `returns true if a site is generated by wordpress`() {
        val html = """
          <html>
            <head>
              <meta name="generator" value="WordPress 4.7-alpha-38592">
            <head>
          </html>
        """
        val doc = Doc.load(html, isDocument = false)
        assertEquals(true, isWordpress(doc))
    }
}
